import pytest


ADMIN_EMAIL = "admin_forms_test@example.com"
ADMIN_PASSWORD = "AdminPassword@123"

USER_EMAIL = "user_forms_test@example.com"
USER_PASSWORD = "UserPassword@123"


@pytest.fixture
def admin_token(client):
    response = client.post(
        "/api/auth/login",
        data={
            "username": ADMIN_EMAIL,
            "password": ADMIN_PASSWORD,
        },
    )

    assert response.status_code == 200

    return response.json()["data"]["access_token"]


@pytest.fixture
def user_token(client):
    response = client.post(
        "/api/auth/login",
        data={
            "username": USER_EMAIL,
            "password": USER_PASSWORD,
        },
    )

    assert response.status_code == 200

    return response.json()["data"]["access_token"]


@pytest.fixture
def test_activity_log(client, admin_token):
    """
    Create an activity log indirectly by performing
    an operation that should be logged by the application.
    """

    headers = {
        "Authorization": f"Bearer {admin_token}"
    }

    response = client.post(
        "/api/forms",
        headers=headers,
        json={
            "title": "Activity Logs API Test Form",
            "description": "Form used for activity log testing",
            "is_active": True,
        },
    )

    assert response.status_code in (200, 201)

    form = response.json()["data"]

    # Fetch activity logs generated by the form creation.
    logs_response = client.get(
        "/api/activity-logs",
        headers=headers,
    )

    assert logs_response.status_code == 200

    data = logs_response.json()["data"]

    if isinstance(data, dict):
        logs = data.get(
            "items",
            data.get("logs", [])
        )
    else:
        logs = data

    assert logs

    return logs[0]


# ============================================================
# GET /api/activity-logs
# ============================================================

def test_list_activity_logs(
    client,
    admin_token,
    test_activity_log,
):
    headers = {
        "Authorization": f"Bearer {admin_token}"
    }

    response = client.get(
        "/api/activity-logs",
        headers=headers,
    )

    assert response.status_code == 200

    body = response.json()

    assert body["success"] is True
    assert "data" in body


def test_list_activity_logs_pagination(
    client,
    admin_token,
    test_activity_log,
):
    headers = {
        "Authorization": f"Bearer {admin_token}"
    }

    response = client.get(
        "/api/activity-logs",
        headers=headers,
        params={
            "page": 1,
            "page_size": 10,
        },
    )

    assert response.status_code == 200

    body = response.json()

    assert body["success"] is True
    assert "data" in body


def test_list_activity_logs_page_two(
    client,
    admin_token,
):
    headers = {
        "Authorization": f"Bearer {admin_token}"
    }

    response = client.get(
        "/api/activity-logs",
        headers=headers,
        params={
            "page": 2,
            "page_size": 10,
        },
    )

    assert response.status_code == 200

    body = response.json()

    assert body["success"] is True


# ============================================================
# GET /api/activity-logs/{log_id}
# ============================================================

def test_get_activity_log(
    client,
    admin_token,
    test_activity_log,
):
    headers = {
        "Authorization": f"Bearer {admin_token}"
    }

    log_id = test_activity_log["id"]

    response = client.get(
        f"/api/activity-logs/{log_id}",
        headers=headers,
    )

    assert response.status_code == 200

    body = response.json()

    assert body["success"] is True
    assert "data" in body


def test_get_activity_log_not_found(
    client,
    admin_token,
):
    headers = {
        "Authorization": f"Bearer {admin_token}"
    }

    response = client.get(
        "/api/activity-logs/999999",
        headers=headers,
    )

    assert response.status_code == 404


# ============================================================
# Activity Log Data
# ============================================================

def test_activity_log_contains_id(
    client,
    admin_token,
    test_activity_log,
):
    headers = {
        "Authorization": f"Bearer {admin_token}"
    }

    response = client.get(
        f"/api/activity-logs/{test_activity_log['id']}",
        headers=headers,
    )

    assert response.status_code == 200

    data = response.json()["data"]

    assert "id" in data


def test_activity_log_contains_action(
    client,
    admin_token,
    test_activity_log,
):
    headers = {
        "Authorization": f"Bearer {admin_token}"
    }

    response = client.get(
        f"/api/activity-logs/{test_activity_log['id']}",
        headers=headers,
    )

    assert response.status_code == 200

    data = response.json()["data"]

    assert "action" in data


def test_activity_log_contains_entity_type(
    client,
    admin_token,
    test_activity_log,
):
    headers = {
        "Authorization": f"Bearer {admin_token}"
    }

    response = client.get(
        f"/api/activity-logs/{test_activity_log['id']}",
        headers=headers,
    )

    assert response.status_code == 200

    data = response.json()["data"]

    assert "entity_type" in data


def test_activity_log_contains_entity_id(
    client,
    admin_token,
    test_activity_log,
):
    headers = {
        "Authorization": f"Bearer {admin_token}"
    }

    response = client.get(
        f"/api/activity-logs/{test_activity_log['id']}",
        headers=headers,
    )

    assert response.status_code == 200

    data = response.json()["data"]

    assert "entity_id" in data


def test_activity_log_contains_description(
    client,
    admin_token,
    test_activity_log,
):
    headers = {
        "Authorization": f"Bearer {admin_token}"
    }

    response = client.get(
        f"/api/activity-logs/{test_activity_log['id']}",
        headers=headers,
    )

    assert response.status_code == 200

    data = response.json()["data"]

    assert "description" in data


def test_activity_log_contains_created_at(
    client,
    admin_token,
    test_activity_log,
):
    headers = {
        "Authorization": f"Bearer {admin_token}"
    }

    response = client.get(
        f"/api/activity-logs/{test_activity_log['id']}",
        headers=headers,
    )

    assert response.status_code == 200

    data = response.json()["data"]

    assert "created_at" in data


# ============================================================
# Authentication
# ============================================================

def test_list_activity_logs_requires_auth(client):
    response = client.get(
        "/api/activity-logs"
    )

    assert response.status_code in (401, 403)


def test_get_activity_log_requires_auth(
    client,
    test_activity_log,
):
    response = client.get(
        f"/api/activity-logs/{test_activity_log['id']}"
    )

    assert response.status_code in (401, 403)


# ============================================================
# User Access
# ============================================================

def test_user_activity_logs_access(
    client,
    user_token,
):
    headers = {
        "Authorization": f"Bearer {user_token}"
    }

    response = client.get(
        "/api/activity-logs",
        headers=headers,
    )

    assert response.status_code in (200, 403)


def test_user_get_activity_log_access(
    client,
    user_token,
    test_activity_log,
):
    headers = {
        "Authorization": f"Bearer {user_token}"
    }

    response = client.get(
        f"/api/activity-logs/{test_activity_log['id']}",
        headers=headers,
    )

    assert response.status_code in (200, 403)


# ============================================================
# Activity Log Generation
# ============================================================

def test_form_creation_generates_activity_log(
    client,
    admin_token,
):
    headers = {
        "Authorization": f"Bearer {admin_token}"
    }

    form_response = client.post(
        "/api/forms",
        headers=headers,
        json={
            "title": "Activity Log Creation Test Form",
            "description": "Testing activity log creation",
            "is_active": True,
        },
    )

    assert form_response.status_code in (200, 201)

    form = form_response.json()["data"]

    logs_response = client.get(
        "/api/activity-logs",
        headers=headers,
    )

    assert logs_response.status_code == 200

    data = logs_response.json()["data"]

    if isinstance(data, dict):
        logs = data.get(
            "items",
            data.get("logs", [])
        )
    else:
        logs = data

    matching_logs = [
        log
        for log in logs
        if str(log.get("entity_id")) == str(form["id"])
    ]

    assert matching_logs


def test_form_update_generates_activity_log(
    client,
    admin_token,
):
    headers = {
        "Authorization": f"Bearer {admin_token}"
    }

    create_response = client.post(
        "/api/forms",
        headers=headers,
        json={
            "title": "Activity Log Update Test Form",
            "description": "Original description",
            "is_active": True,
        },
    )

    assert create_response.status_code in (200, 201)

    form = create_response.json()["data"]

    update_response = client.put(
        f"/api/forms/{form['id']}",
        headers=headers,
        json={
            "title": "Activity Log Updated Form",
            "description": "Updated description",
            "is_active": True,
        },
    )

    assert update_response.status_code in (200, 201)

    logs_response = client.get(
        "/api/activity-logs",
        headers=headers,
    )

    assert logs_response.status_code == 200

    data = logs_response.json()["data"]

    if isinstance(data, dict):
        logs = data.get(
            "items",
            data.get("logs", [])
        )
    else:
        logs = data

    matching_logs = [
        log
        for log in logs
        if str(log.get("entity_id")) == str(form["id"])
    ]

    assert matching_logs


def test_form_delete_generates_activity_log(
    client,
    admin_token,
):
    headers = {
        "Authorization": f"Bearer {admin_token}"
    }

    create_response = client.post(
        "/api/forms",
        headers=headers,
        json={
            "title": "Activity Log Delete Test Form",
            "description": "Form for delete log testing",
            "is_active": True,
        },
    )

    assert create_response.status_code in (200, 201)

    form = create_response.json()["data"]

    form_id = form["id"]

    delete_response = client.delete(
        f"/api/forms/{form_id}",
        headers=headers,
    )

    assert delete_response.status_code in (200, 204)

    logs_response = client.get(
        "/api/activity-logs",
        headers=headers,
    )

    assert logs_response.status_code == 200

    data = logs_response.json()["data"]

    if isinstance(data, dict):
        logs = data.get(
            "items",
            data.get("logs", [])
        )
    else:
        logs = data

    matching_logs = [
        log
        for log in logs
        if str(log.get("entity_id")) == str(form_id)
    ]

    assert matching_logs